name: Generate Documentation

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install Modules
        run: npm i
      - name: Generate Documentation
        run: npx documentation build *.js -f md --github --ext .js --o docs
